version: "3.8"
services:
  dream-mate-redis:
    container_name: dream-mate-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: taedy/dream-mate-redis
    ports:
      - "6379:6379"
  dream-mate-database:
    container_name: dream-mate-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: taedy/dream-mate-database
    environment:
      - MYSQL_DATABASE=dreammate
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"