spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreammate
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: DreamMate-application-2023.secret_key
  token.expired-time-ms: 2592000000 # 30 days


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dream-mate-database:3306/dreammate
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: dream-mate-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: DreamMate-application-2023.secret_key
  token.expired-time-ms: 2592000000 # 30 days

dream:
  mate:
    base:
      url: http://13.209.32.116/dir/

      # /dir/은 경로(path)를 나타냅니다. 이것은 웹 서버 상의 특정 디렉토리를 가리키거나, 어플리케이션 내에서 특정한 라우트를 의미할 수 있습니다.
      #특정 디렉토리나 경로를 URL에 포함하는 것은 해당 URL이 서버 내부에서 특정 디렉토리로 라우팅되거나, 애플리케이션 내의 특정한 엔드포인트로 매핑되도록 하는 역할을 합니다.
      # 이를 통해 서버 내에서 어떤 리소스를 호출하는지 명시적으로 지정할 수 있습니다.
      #따라서 http://13.209.32.116/dir/과 같은 URL은 탄력적 IP 주소에 /dir/이라는 디렉토리(경로)에 있는 리소스에 접근하도록 지시하는 것입니다.